In [1]:
import pandas as pd
import numpy as np

In [2]:
movies= pd.read_csv("imdb-top-1000.csv")
movies.head()

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0

In [3]:
### groupby -> apply on categorial data

genre=movies.groupby('Genre')

In [4]:
genre.max()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,Yôjinbô,2019,321,9.0,Zack Snyder,Yun-Fat Chow,2303232,936662225.0,98.0
Adventure,Zombieland,PG,228,8.6,Ömer Faruk Sorak,Yves Montand,1512360,874211619.0,100.0
Animation,Ôkami kodomo no Ame to Yuki,2020,137,8.6,Yoshifumi Kondô,Yôji Matsuda,999790,873839108.0,96.0
Biography,Zerkalo,2020,209,8.9,Tom McCarthy,Éric Toledano,1213505,753585104.0,97.0
Comedy,Zindagi Na Milegi Dobara,2020,188,8.6,Zoya Akhtar,Ömer Faruk Sorak,939631,886752933.0,99.0
Crime,À bout de souffle,2019,229,9.2,Yavuz Turgul,Vincent Cassel,1826188,790482117.0,100.0
Drama,Zwartboek,2020,242,9.3,Çagan Irmak,Çetin Tekindor,2343110,924558264.0,100.0
Family,Willy Wonka & the Chocolate Factory,1982,115,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
Fantasy,Nosferatu,1922,94,8.1,Robert Wiene,Werner Krauss,88794,445151978.0,NaN
Film-Noir,The Third Man,1949,108,8.1,John Huston,Teresa Wright,158731,123353292.0,97.0
Horror,The Thing,2017,122,8.5,William Friedkin,Sigourney Weaver,787806,298791505.0,97.0
Mystery,Vertigo,2012,138,8.4,Terry Gilliam,Vidya Balan,1129894,474203697.0,100.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,The Outlaw Josey Wales,1976,165,8.8,Sergio Leone,Henry Fonda,688390,31800000.0,90.0

In [18]:
## top 3 gross earning 
movies.groupby('Genre')["Gross"].sum().sort_values(ascending=False).head(3)

Genre
Drama     3.540997e+10
Action    3.263226e+10
Comedy    1.566387e+10
Name: Gross, dtype: float64

In [19]:
##
movies.groupby("Genre")["IMDB_Rating"].mean().sort_values(ascending=False).head()

Genre
Western      8.350000
Crime        8.016822
Fantasy      8.000000
Mystery      7.975000
Film-Noir    7.966667
Name: IMDB_Rating, dtype: float64

In [20]:
movies.groupby("Director")["No_of_Votes"].sum().sort_values(ascending=False).head(3)

Director
Christopher Nolan    11578345
Quentin Tarantino     8123208
Steven Spielberg      7817166
Name: No_of_Votes, dtype: int64

In [21]:
movies["Star1"].value_counts()

Star1
Tom Hanks            12
Robert De Niro       11
Al Pacino            10
Clint Eastwood       10
Humphrey Bogart       9
                     ..
Phil Harris           1
David Hemmings        1
John Lennon           1
Tallulah Bankhead     1
Bruce Lee             1
Name: count, Length: 660, dtype: int64

In [23]:
# or 
movies.groupby("Star1")["Series_Title"].count().sort_values(ascending=False)

Star1
Tom Hanks               12
Robert De Niro          11
Clint Eastwood          10
Al Pacino               10
Humphrey Bogart          9
                        ..
Zbigniew Zamachowski     1
Zooey Deschanel          1
Çetin Tekindor           1
Éric Toledano            1
Aaron Taylor-Johnson     1
Name: Series_Title, Length: 660, dtype: int64

In [24]:
movies.groupby("Genre").size()

Genre
Action       172
Adventure     72
Animation     82
Biography     88
Comedy       155
Crime        107
Drama        289
Family         2
Fantasy        2
Film-Noir      3
Horror        11
Mystery       12
Thriller       1
Western        4
dtype: int64

In [25]:
movies["Genre"].value_counts()

Genre
Drama        289
Action       172
Comedy       155
Crime        107
Biography     88
Animation     82
Adventure     72
Mystery       12
Horror        11
Western        4
Film-Noir      3
Fantasy        2
Family         2
Thriller       1
Name: count, dtype: int64

In [26]:
genre=movies.groupby('Genre')

In [28]:
len(genre)
## or 
movies["Genre"].nunique()

14

In [31]:
genre.first() ## get first row of each group
genre.last()  ## get last row of each group
genre.nth(4)   ## get nth row of each group

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
13,The Lord of the Rings: The Two Towers,2002,179,Action,8.7,Peter Jackson,Elijah Wood,1485555,342551365.0,87.0
20,Soorarai Pottru,2020,153,Drama,8.6,Sudha Kongara,Suriya,54995,556832648.0,NaN
22,Cidade de Deus,2002,130,Crime,8.6,Fernando Meirelles,Kátia Lund,699256,7563397.0,79.0
38,The Pianist,2002,150,Biography,8.5,Roman Polanski,Adrien Brody,729603,32572577.0,85.0
58,Spider-Man: Into the Spider-Verse,2018,117,Animation,8.4,Bob Persichetti,Peter Ramsey,375110,190241310.0,87.0
64,3 Idiots,2009,170,Comedy,8.4,Rajkumar Hirani,Aamir Khan,344445,6532908.0,67.0
114,2001: A Space Odyssey,1968,149,Adventure,8.3,Stanley Kubrick,Keir Dullea,603517,56954992.0,84.0
220,Kahaani,2012,122,Mystery,8.1,Sujoy Ghosh,Vidya Balan,57806,1035953.0,NaN
544,Night of the Living Dead,1968,96,Horror,7.9,George A. Romero,Duane Jones,116557,89029.0,89.0

In [38]:
movies[movies["Genre"]=="Action"].head(2)
## or
genre.get_group("Action").head(2)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
5,The Lord of the Rings: The Return of the King,2003,201,Action,8.9,Peter Jackson,Elijah Wood,1642758,377845905.0,94.0

In [ ]:
genre.groups   ## get all index of every gruop's rows

{'Action': [2, 5, 8, 10, 13, 14, 16, 29, 30, 31, 39, 42, 44, 55, 57, 59, 60, 63, 68, 72, 106, 109, 129, 130, 134, 140, 142, 144, 152, 155, 160, 161, 166, 168, 171, 172, 177, 181, 194, 201, 202, 216, 217, 223, 224, 236, 241, 262, 275, 294, 308, 320, 325, 326, 331, 337, 339, 340, 343, 345, 348, 351, 353, 356, 357, 362, 368, 369, 375, 376, 390, 410, 431, 436, 473, 477, 479, 482, 488, 493, 496, 502, 507, 511, 532, 535, 540, 543, 564, 569, 570, 573, 577, 582, 583, 602, 605, 608, 615, 623, ...], 'Adventure': [21, 47, 93, 110, 114, 116, 118, 137, 178, 179, 191, 193, 209, 226, 231, 247, 267, 273, 281, 300, 301, 304, 306, 323, 329, 361, 366, 377, 402, 406, 415, 426, 458, 470, 497, 498, 506, 513, 514, 537, 549, 552, 553, 566, 576, 604, 609, 618, 638, 647, 675, 681, 686, 692, 711, 713, 739, 755, 781, 797, 798, 851, 873, 884, 912, 919, 947, 957, 964, 966, 984, 991], 'Animation': [23, 43, 46, 56, 58, 61, 66, 70, 101, 135, 146, 151, 158, 170, 197, 205, 211, 213, 219, 229, 230, 242, 245, 246, 270, 330, 332, 358, 367, 378, 386, 389, 394, 395, 399, 401, 405, 409, 469, 499, 510, 516, 518, 522, 578, 586, 592, 595, 596, 599, 633, 640, 643, 651, 665, 672, 694, 728, 740, 741, 744, 756, 758, 761, 771, 783, 796, 799, 822, 828, 843, 875, 891, 892, 902, 906, 920, 956, 971, 976, 986, 992], 'Biography': [7, 15, 18, 35, 38, 54, 102, 107, 131, 139, 147, 157, 159, 173, 176, 212, 215, 218, 228, 235, 243, 263, 276, 282, 290, 298, 317, 328, 338, 342, 346, 359, 360, 365, 372, 373, 385, 411, 416, 418, 424, 429, 484, 525, 536, 542, 545, 575, 579, 587, 600, 606, 614, 622, 632, 635, 644, 649, 650, 657, 671, 673, 684, 729, 748, 753, 757, 759, 766, 770, 779, 809, 810, 815, 820, 831, 849, 858, 877, 882, 897, 910, 915, 923, 940, 949, 952, 987], 'Comedy': [19, 26, 51, 52, 64, 78, 83, 95, 96, 112, 117, 120, 127, 128, 132, 153, 169, 183, 192, 204, 207, 208, 214, 221, 233, 238, 240, 250, 251, 252, 256, 261, 266, 277, 284, 311, 313, 316, 318, 322, 327, 374, 379, 381, 392, 396, 403, 413, 414, 417, 427, 435, 445, 446, 449, 455, 459, 460, 463, 464, 466, 471, 472, 475, 481, 490, 494, 500, 503, 509, 526, 528, 530, 531, 533, 538, 539, 541, 547, 557, 558, 562, 563, 565, 574, 591, 593, 594, 598, 613, 626, 630, 660, 662, 667, 679, 680, 683, 687, 701, ...], 'Crime': [1, 3, 4, 6, 22, 25, 27, 28, 33, 37, 41, 71, 77, 79, 86, 87, 103, 108, 111, 113, 123, 125, 133, 136, 162, 163, 164, 165, 180, 186, 187, 189, 198, 222, 232, 239, 255, 257, 287, 288, 299, 305, 335, 363, 364, 380, 384, 397, 437, 438, 441, 442, 444, 450, 451, 465, 474, 480, 485, 487, 505, 512, 519, 520, 523, 527, 546, 556, 560, 584, 597, 603, 607, 611, 621, 639, 653, 664, 669, 676, 695, 708, 723, 762, 763, 767, 775, 791, 795, 802, 811, 823, 827, 833, 885, 895, 921, 922, 926, 938, ...], 'Drama': [0, 9, 11, 17, 20, 24, 32, 34, 36, 40, 45, 50, 53, 62, 65, 67, 73, 74, 76, 80, 82, 84, 85, 88, 89, 90, 91, 92, 94, 97, 98, 99, 100, 104, 105, 121, 122, 124, 126, 138, 141, 143, 148, 149, 150, 154, 156, 167, 174, 175, 182, 184, 185, 188, 190, 195, 196, 199, 200, 203, 206, 210, 225, 227, 234, 237, 244, 248, 249, 253, 254, 258, 259, 260, 264, 265, 268, 269, 272, 274, 278, 279, 280, 283, 285, 286, 289, 291, 292, 293, 295, 296, 297, 302, 303, 307, 310, 312, 314, 315, ...], 'Family': [688, 698], 'Fantasy': [321, 568], 'Film-Noir': [309, 456, 712], 'Horror': [49, 75, 271, 419, 544, 707, 724, 844, 876, 932, 948], 'Mystery': [69, 81, 119, 145, 220, 393, 420, 714, 829, 899, 959, 961], 'Thriller': [700], 'Western': [12, 48, 115, 691]}

In [42]:
genre.describe()

          Runtime                                                              \
            count        mean        std    min     25%    50%     75%    max
Genre
Action      172.0  129.046512  28.500706   45.0  110.75  127.5  143.25  321.0
Adventure    72.0  134.111111  33.317320   88.0  109.00  127.0  149.00  228.0
Animation    82.0   99.585366  14.530471   71.0   90.00   99.5  106.75  137.0
Biography    88.0  136.022727  25.514466   93.0  120.00  129.0  146.25  209.0
Comedy      155.0  112.129032  22.946213   68.0   96.00  106.0  124.50  188.0
Crime       107.0  126.392523  27.689231   80.0  106.50  122.0  141.50  229.0
Drama       289.0  124.737024  27.740490   64.0  105.00  121.0  137.00  242.0
Family        2.0  107.500000  10.606602  100.0  103.75  107.5  111.25  115.0
Fantasy       2.0   85.000000  12.727922   76.0   80.50   85.0   89.50   94.0
Film-Noir     3.0  104.000000   4.000000  100.0  102.00  104.0  106.00  108.0
Horror       11.0  102.090909  13.604812   71.0   98.00  103.0  109.00  122.0
Mystery      12.0  119.083333  14.475423   96.0  110.75  117.5  130.25  138.0
Thriller      1.0  108.000000        NaN  108.0  108.00  108.0  108.00  108.0
Western       4.0  148.250000  17.153717  132.0  134.25  148.0  162.00  165.0

          IMDB_Rating            ...         Gross              Metascore  \
                count      mean  ...           75%          max     count
Genre                            ...
Action          172.0  7.949419  ...  2.674437e+08  936662225.0     143.0
Adventure        72.0  7.937500  ...  1.998070e+08  874211619.0      64.0
Animation        82.0  7.930488  ...  2.520612e+08  873839108.0      75.0
Biography        88.0  7.938636  ...  9.829924e+07  753585104.0      79.0
Comedy          155.0  7.901290  ...  8.107809e+07  886752933.0     125.0
Crime           107.0  8.016822  ...  7.102163e+07  790482117.0      87.0
Drama           289.0  7.957439  ...  1.164461e+08  924558264.0     241.0
Family            2.0  7.800000  ...  3.273329e+08  435110554.0       2.0
Fantasy           2.0  8.000000  ...  4.182577e+08  445151978.0       0.0
Film-Noir         3.0  7.966667  ...  6.273068e+07  123353292.0       3.0
Horror           11.0  7.909091  ...  1.362817e+08  298791505.0      11.0
Mystery          12.0  7.975000  ...  1.310949e+08  474203697.0       8.0
Thriller          1.0  7.800000  ...  1.755074e+07   17550741.0       1.0
Western           4.0  8.350000  ...  1.920000e+07   31800000.0       4.0


                mean        std   min    25%   50%    75%    max
Genre
Action     73.419580  12.421252  33.0  65.00  74.0  82.00   98.0
Adventure  78.437500  12.345393  41.0  69.75  80.5  87.25  100.0
Animation  81.093333   8.813646  61.0  75.00  82.0  87.50   96.0
Biography  76.240506  11.028187  48.0  70.50  76.0  84.50   97.0
Comedy     78.720000  11.829160  45.0  72.00  79.0  88.00   99.0
Crime      77.080460  13.099102  47.0  69.50  77.0  87.00  100.0
Drama      79.701245  12.744687  28.0  72.00  82.0  89.00  100.0
Family     79.000000  16.970563  67.0  73.00  79.0  85.00   91.0
Fantasy          NaN        NaN   NaN    NaN   NaN    NaN    NaN
Film-Noir  95.666667   1.527525  94.0  95.00  96.0  96.50   97.0
Horror     80.000000  15.362291  46.0  77.50  87.0  88.50   97.0
Mystery    79.125000  18.604435  52.0  65.25  77.0  98.50  100.0
Thriller   81.000000        NaN  81.0  81.00  81.0  81.00   81.0
Western    78.250000   9.032349  69.0  72.75  77.0  82.50   90.0

[14 rows x 40 columns]

In [45]:
genre.sample(2,replace=True) ## get random movies from every grups

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
718,Scarface: The Shame of the Nation,1932,93,Action,7.8,Howard Hawks,Richard Rosson,25312,82900837.0,87.0
13,The Lord of the Rings: The Two Towers,2002,179,Action,8.7,Peter Jackson,Elijah Wood,1485555,342551365.0,87.0
93,Inglourious Basterds,2009,153,Adventure,8.3,Quentin Tarantino,Brad Pitt,1267869,120540719.0,69.0
681,The Goonies,1985,114,Adventure,7.8,Richard Donner,Sean Astin,244430,61503218.0,62.0
245,"Monsters, Inc.",2001,92,Animation,8.1,Pete Docter,David Silverman,815505,289916256.0,79.0
246,Shin seiki Evangelion Gekijô-ban: Air/Magokoro...,1997,87,Animation,8.1,Hideaki Anno,Kazuya Tsurumaki,38847,364744762.0,NaN
536,All the President's Men,1976,138,Biography,7.9,Alan J. Pakula,Dustin Hoffman,103031,70600000.0,84.0
424,Butch Cassidy and the Sundance Kid,1969,110,Biography,8.0,George Roy Hill,Paul Newman,201888,102308889.0,66.0
284,Paper Moon,1973,102,Comedy,8.1,Peter Bogdanovich,Ryan O'Neal,42285,30933743.0,77.0
687,The King of Comedy,1982,109,Comedy,7.8,Martin Scorsese,Robert De Niro,88511,2500000.0,73.0
560,The Big Sleep,1946,114,Crime,7.9,Howard Hawks,Humphrey Bogart,78796,6540000.0,NaN
669,Boyz n the Hood,1991,112,Crime,7.8,John Singleton,Cuba Gooding Jr.,126082,57504069.0,76.0
292,El ángel exterminador,1962,95,Drama,8.1,Luis Buñuel,Silvia Pinal,29682,345262196.0,NaN
407,Der Himmel über Berlin,1987,128,Drama,8.0,Wim Wenders,Bruno Ganz,64722,3333969.0,79.0
698,Willy Wonka & the Chocolate Factory,1971,100,Family,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
698,Willy Wonka & the Chocolate Factory,1971,100,Family,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
568,Nosferatu,1922,94,Fantasy,7.9,F.W. Murnau,Max Schreck,88794,445151978.0,NaN
321,Das Cabinet des Dr. Caligari,1920,76,Fantasy,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
309,The Third Man,1949,104,Film-Noir,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
712,Shadow of a Doubt,1943,108,Film-Noir,7.8,Alfred Hitchcock,Teresa Wright,59556,123353292.0,94.0
419,The Exorcist,1973,122,Horror,8.0,William Friedkin,Ellen Burstyn,362393,232906145.0,81.0
876,The Invisible Man,1933,71,Horror,7.7,James Whale,Claude Rains,30683,298791505.0,87.0
69,Memento,2000,113,Mystery,8.4,Christopher Nolan,Guy Pearce,1125712,25544867.0,80.0
714,The Lady Vanishes,1938,96,Mystery,7.8,Alfred Hitchcock,Margaret Lockwood,47400,474203697.0,98.0
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
12,"Il buono, il brutto, il cattivo",1966,161,Western,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0
115,Per qualche dollaro in più,1965,132,Western,8.3,Sergio Leone,Clint Eastwood,232772,15000000.0,74.0

In [46]:
genre.nunique()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,172,61,78,15,123,121,172,172,50
Adventure,72,49,58,10,59,59,72,72,33
Animation,82,35,41,11,51,77,82,82,29
Biography,88,44,56,13,76,72,88,88,40
Comedy,155,72,70,11,113,133,155,155,44
Crime,106,56,65,14,86,85,107,107,39
Drama,289,83,95,14,211,250,288,287,52
Family,2,2,2,1,2,2,2,2,2
Fantasy,2,2,2,2,2,2,2,2,0
Film-Noir,3,3,3,3,3,3,3,3,3
Horror,11,11,10,8,10,11,11,11,9
Mystery,12,11,10,8,10,11,12,12,7
Thriller,1,1,1,1,1,1,1,1,1
Western,4,4,4,4,2,2,4,4,4

In [ ]:
## aggregate -> different operation on diff cols of every grops

genre.agg({
    "Runtime":"mean",
    "IMDB_Rating":"min",
    "No_of_Votes":"std"
})

              Runtime  IMDB_Rating    No_of_Votes
Genre
Action     129.046512          7.6  432946.814748
Adventure  134.111111          7.6  301188.347642
Animation   99.585366          7.6  262173.231571
Biography  136.022727          7.6  271284.191372
Comedy     112.129032          7.6  188653.570564
Crime      126.392523          7.6  373999.730656
Drama      124.737024          7.6  305554.162841
Family     107.500000          7.8  137008.302816
Fantasy     85.000000          7.9   22179.111299
Film-Noir  104.000000          7.8   54649.083277
Horror     102.090909          7.6  234883.508691
Mystery    119.083333          7.6  404621.915297
Thriller   108.000000          7.8            NaN
Western    148.250000          7.8  263489.554280

In [53]:
genre.agg(["sum","max","min"])

                                                Series_Title  \
                                                         sum
Genre
Action     The Dark KnightThe Lord of the Rings: The Retu...
Adventure  InterstellarBack to the FutureInglourious Bast...
Animation  Sen to Chihiro no kamikakushiThe Lion KingHota...
Biography  Schindler's ListGoodfellasHamiltonThe Intoucha...
Comedy     GisaengchungLa vita è bellaModern TimesCity Li...
Crime      The GodfatherThe Godfather: Part II12 Angry Me...
Drama      The Shawshank RedemptionFight ClubForrest Gump...
Family     E.T. the Extra-TerrestrialWilly Wonka & the Ch...
Fantasy                Das Cabinet des Dr. CaligariNosferatu
Film-Noir   The Third ManThe Maltese FalconShadow of a Doubt
Horror     PsychoAlienThe ThingThe ExorcistNight of the L...
Mystery    MementoRear WindowVertigoShutter IslandKahaani...
Thriller                                     Wait Until Dark
Western    Il buono, il brutto, il cattivoOnce Upon a Tim...

                                                \
                                           max
Genre
Action                                 Yôjinbô
Adventure                           Zombieland
Animation          Ôkami kodomo no Ame to Yuki
Biography                              Zerkalo
Comedy                Zindagi Na Milegi Dobara
Crime                        À bout de souffle
Drama                                Zwartboek
Family     Willy Wonka & the Chocolate Factory
Fantasy                              Nosferatu
Film-Noir                        The Third Man
Horror                               The Thing
Mystery                                Vertigo
Thriller                       Wait Until Dark
Western                 The Outlaw Josey Wales

                                            \
                                       min
Genre
Action                                 300
Adventure            2001: A Space Odyssey
Animation                            Akira
Biography                 12 Years a Slave
Comedy                (500) Days of Summer
Crime                         12 Angry Men
Drama                                 1917
Family          E.T. the Extra-Terrestrial
Fantasy       Das Cabinet des Dr. Caligari
Film-Noir                Shadow of a Doubt
Horror                               Alien
Mystery                          Dark City
Thriller                   Wait Until Dark
Western    Il buono, il brutto, il cattivo

                                               Released_Year              \
                                                         sum   max   min
Genre
Action     2008200320102001200219991980197719621954200019...  2019  1924
Adventure  2014198520091981196819621959201319751963194819...    PG  1925
Animation  2001199419882016201820172008199719952019200920...  2020  1940
Biography  1993199020202011200220171995198420182013201320...  2020  1928
Comedy     2019199719361931200919641940200120001973196019...  2020  1921
Crime      1972197419571994200219991995199120192006199519...  2019  1931
Drama      1994199919941975202019981946201420061998198819...  2020  1925
Family                                              19821971  1982  1971
Fantasy                                             19201922  1922  1920
Film-Noir                                       194919411943  1949  1941
Horror          19601979198219731968196120171978193320042001  2017  1933
Mystery     200019541958201020121995197219381988201219981997  2012  1938
Thriller                                                1967  1967  1967
Western                                     1966196819651976  1976  1965

          Runtime           IMDB_Rating  ...                     Star1  \
              sum  max  min         sum  ...                       min
Genre                                    ...
Action      22196  321   45      1367.3  ...                Aamir Khan
Adventure    9656  228   88       571.5  ...                Aamir Khan
Animation    8166  137   71       650.3  ...             Adrian Molina
Biography   11970  209   93       698.6  ...              Adrien Brody
Comedy      17380  188   68      1224.7  ...                Aamir Khan
Crime       13524  229   80       857.8  ...                Ajay Devgn
Drama       36049  242   64      2299.7  ...                Abhay Deol
Family        215  115  100        15.6  ...               Gene Wilder
Fantasy       170   94   76        16.0  ...               Max Schreck
Film-Noir     312  108  100        23.9  ...           Humphrey Bogart
Horror       1123  122   71        87.0  ...           Anthony Perkins
Mystery      1429  138   96        95.7  ...  Bernard-Pierre Donnadieu
Thriller      108  108  108         7.8  ...            Audrey Hepburn
Western       593  165  132        33.4  ...            Clint Eastwood

          No_of_Votes                          Gross               \
                  sum      max     min           sum          max
Genre
Action       72282412  2303232   25312  3.263226e+10  936662225.0
Adventure    22576163  1512360   29999  9.496922e+09  874211619.0
Animation    21978630   999790   25229  1.463147e+10  873839108.0
Biography    24006844  1213505   27254  8.276358e+09  753585104.0
Comedy       27620327   939631   26337  1.566387e+10  886752933.0
Crime        33533615  1826188   27712  8.452632e+09  790482117.0
Drama        61367304  2343110   25088  3.540997e+10  924558264.0
Family         551221   372490  178731  4.391106e+08  435110554.0
Fantasy        146222    88794   57428  7.827267e+08  445151978.0
Film-Noir      367215   158731   59556  1.259105e+08  123353292.0
Horror        3742556   787806   27007  1.034649e+09  298791505.0
Mystery       4203004  1129894   33982  1.256417e+09  474203697.0
Thriller        27733    27733   27733  1.755074e+07   17550741.0
Western       1289665   688390   65659  5.822151e+07   31800000.0

                       Metascore
                   min       sum    max   min
Genre
Action          3296.0   10499.0   98.0  33.0
Adventure      61001.0    5020.0  100.0  41.0
Animation     128985.0    6082.0   96.0  61.0
Biography      21877.0    6023.0   97.0  48.0
Comedy          1305.0    9840.0   99.0  45.0
Crime           6013.0    6706.0  100.0  47.0
Drama           3600.0   19208.0  100.0  28.0
Family       4000000.0     158.0   91.0  67.0
Fantasy    337574718.0       0.0    NaN   NaN
Film-Noir     449191.0     287.0   97.0  94.0
Horror         89029.0     880.0   97.0  46.0
Mystery      1035953.0     633.0  100.0  52.0
Thriller    17550741.0      81.0   81.0  81.0
Western      5321508.0     313.0   90.0  69.0

[14 rows x 27 columns]

In [54]:

genre.agg({
    "Runtime":["mean","sum","min"],
    "IMDB_Rating":"min",
    "No_of_Votes":["std","min","mean"]
})

              Runtime             IMDB_Rating    No_of_Votes          \
                 mean    sum  min         min            std     min
Genre
Action     129.046512  22196   45         7.6  432946.814748   25312
Adventure  134.111111   9656   88         7.6  301188.347642   29999
Animation   99.585366   8166   71         7.6  262173.231571   25229
Biography  136.022727  11970   93         7.6  271284.191372   27254
Comedy     112.129032  17380   68         7.6  188653.570564   26337
Crime      126.392523  13524   80         7.6  373999.730656   27712
Drama      124.737024  36049   64         7.6  305554.162841   25088
Family     107.500000    215  100         7.8  137008.302816  178731
Fantasy     85.000000    170   76         7.9   22179.111299   57428
Film-Noir  104.000000    312  100         7.8   54649.083277   59556
Horror     102.090909   1123   71         7.6  234883.508691   27007
Mystery    119.083333   1429   96         7.6  404621.915297   33982
Thriller   108.000000    108  108         7.8            NaN   27733
Western    148.250000    593  132         7.8  263489.554280   65659


                    mean
Genre
Action     420246.581395
Adventure  313557.819444
Animation  268032.073171
Biography  272805.045455
Comedy     178195.658065
Crime      313398.271028
Drama      212343.612457
Family     275610.500000
Fantasy     73111.000000
Film-Noir  122405.000000
Horror     340232.363636
Mystery    350250.333333
Thriller    27733.000000
Western    322416.250000

## pd.concat() stitches those DataFrames together vertically (row-wise).

On the first loop, it just becomes the filtered data.

On later loops, it stacks the new group’s filtered rows below the existing ones.

In [ ]:
### loop in groups    ## from group we get two type of data -> datafrem(data) and str
df=pd.DataFrame(columns=movies.columns)
for group,data in genre:
    df=pd.concat([df,data[data["IMDB_Rating"]==data["IMDB_Rating"].max()]])

df

C:\Users\susov\AppData\Local\Temp\ipykernel_7676\913308792.py:4: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df=pd.concat([df,data[data["IMDB_Rating"]==data["IMDB_Rating"].max()]])

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
21,Interstellar,2014,169,Adventure,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017.0,74.0
23,Sen to Chihiro no kamikakushi,2001,125,Animation,8.6,Hayao Miyazaki,Daveigh Chase,651376,10055859.0,96.0
7,Schindler's List,1993,195,Biography,8.9,Steven Spielberg,Liam Neeson,1213505,96898818.0,94.0
19,Gisaengchung,2019,132,Comedy,8.6,Bong Joon Ho,Kang-ho Song,552778,53367844.0,96.0
26,La vita è bella,1997,116,Comedy,8.6,Roberto Benigni,Roberto Benigni,623629,57598247.0,59.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
688,E.T. the Extra-Terrestrial,1982,115,Family,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
698,Willy Wonka & the Chocolate Factory,1971,100,Family,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
321,Das Cabinet des Dr. Caligari,1920,76,Fantasy,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
309,The Third Man,1949,104,Film-Noir,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
49,Psycho,1960,109,Horror,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
69,Memento,2000,113,Mystery,8.4,Christopher Nolan,Guy Pearce,1125712,25544867.0,80.0
81,Rear Window,1954,112,Mystery,8.4,Alfred Hitchcock,James Stewart,444074,36764313.0,100.0
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
12,"Il buono, il brutto, il cattivo",1966,161,Western,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0

In [75]:
def hoo(group):
    print(group[group["Series_Title"].str.startswith("A")])


genre.apply(hoo)

                 Series_Title Released_Year  Runtime   Genre  IMDB_Rating  \
59          Avengers: Endgame          2019      181  Action          8.4
60     Avengers: Infinity War          2018      149  Action          8.4
106                    Aliens          1986      137  Action          8.3
166           Andaz Apna Apna          1994      160  Action          8.2
224               A Wednesday          2008      104  Action          8.1
540  Aguirre, der Zorn Gottes          1972       95  Action          7.9
602      Ang-ma-reul bo-at-da          2010      144  Action          7.8
605                   Ajeossi          2010      119  Action          7.8
623                    Avatar          2009      162  Action          7.8
625                Apocalypto          2006      139  Action          7.8

              Director             Star1  No_of_Votes        Gross  Metascore
59       Anthony Russo         Joe Russo       809955  858373000.0       78.0
60       Anthony Russo         Joe Russo       834477  678815482.0       68.0
106      James Cameron  Sigourney Weaver       652719   85160248.0       84.0
166  Rajkumar Santoshi        Aamir Khan        49300  213351844.0        NaN
224      Neeraj Pandey       Anupam Kher        73891  573329738.0        NaN
540      Werner Herzog      Klaus Kinski        52397  508046921.0        NaN
602       Jee-woon Kim     Lee Byung-Hun       111252     128392.0       67.0
605     Jeong-beom Lee           Won Bin        62848       6460.0        NaN
623      James Cameron   Sam Worthington      1118998  760507625.0       83.0
625         Mel Gibson  Gerardo Taracena       291018   50866635.0       68.0
      Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
514  Almost Famous          2000      122  Adventure          7.9
966      Apollo 13            PG      140  Adventure          7.6

          Director         Star1  No_of_Votes        Gross  Metascore
514  Cameron Crowe  Billy Crudup       252586   32534850.0       90.0
966     Ron Howard     Tom Hanks       269197  173837933.0       77.0
    Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
399      Aladdin          1992       90  Animation          8.0
405        Akira          1988      124  Animation          8.0

            Director         Star1  No_of_Votes        Gross  Metascore
399     Ron Clements   John Musker       373845  217350219.0       86.0
405  Katsuhiro Ôtomo  Mitsuo Iwata       164918     553171.0        NaN
                  Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
54   Ayla: The Daughter of War          2017      125  Biography          8.4
107                    Amadeus          1984      160  Biography          8.3
159           A Beautiful Mind          2001      135  Biography          8.2
290              Andrei Rublev          1966      205  Biography          8.1
536    All the President's Men          1976      138  Biography          7.9
622          American Gangster          2007      157  Biography          7.8
671                 Awakenings          1990      121  Biography          7.8
753                       Argo          2012      120  Biography          7.7
858      A Man for All Seasons          1966      120  Biography          7.7

             Director                Star1  No_of_Votes        Gross  \
54          Can Ulkay            Erdem Can        34112  679278040.0
107      Milos Forman    F. Murray Abraham       369007   51973029.0
159        Ron Howard        Russell Crowe       848920  170742341.0
290  Andrei Tarkovsky  Anatoliy Solonitsyn        46947     102021.0
536    Alan J. Pakula       Dustin Hoffman       103031   70600000.0
622      Ridley Scott    Denzel Washington       392449  130164645.0
671    Penny Marshall       Robert De Niro       125276   52096475.0
753       Ben Affleck          Ben Affleck       572581  136025503.0
858    Fred Zinnemann        Paul Scofield        31222   28350000.0

     Metascore
54         NaN
107       88.0
159       72.0
290        NaN
536       84.0
622       76.0
671       74.0
753       86.0
858       72.0
             Series_Title Released_Year  Runtime   Genre  IMDB_Rating  \
95                 Amélie          2001      122  Comedy          8.3
414            Annie Hall          1977       93  Comedy          8.0
455  Arsenic and Old Lace          1942      118  Comedy          8.0
531     A Christmas Story          1983       93  Comedy          7.9
538              Amarcord          1973      123  Comedy          7.9
565  A Night at the Opera          1935       96  Comedy          7.9
593            About Time          2013      123  Comedy          7.8
630           Adams æbler          2005       94  Comedy          7.8
789           Adaptation.          2002      115  Comedy          7.7
806    As Good as It Gets          1997      139  Comedy          7.7
836           After Hours          1985       97  Comedy          7.7
842             Airplane!          1980       88  Comedy          7.7
953       American Psycho          2000      101  Comedy          7.6
994    A Hard Day's Night          1964       87  Comedy          7.6

                 Director              Star1  No_of_Votes        Gross  \
95     Jean-Pierre Jeunet      Audrey Tautou       703810   33225499.0
414           Woody Allen        Woody Allen       251823   39200000.0
455           Frank Capra         Cary Grant        65101  460853100.0
531             Bob Clark  Peter Billingsley       132947   20605209.0
538      Federico Fellini        Magali Noël        39897  882861253.0
565              Sam Wood    Edmund Goulding        30580    2537520.0
593        Richard Curtis   Domhnall Gleeson       303032   15322921.0
630  Anders Thomas Jensen     Ulrich Thomsen        45717       1305.0
789           Spike Jonze       Nicolas Cage       178565   22245861.0
806       James L. Brooks     Jack Nicholson       275755  148478011.0
836       Martin Scorsese      Griffin Dunne        59635   10600000.0
842          Jim Abrahams       David Zucker       214882   83400000.0
953           Mary Harron     Christian Bale       490062   15070285.0
994        Richard Lester        John Lennon        40351   13780024.0

     Metascore
95        69.0
414       92.0
455        NaN
531       77.0
538        NaN
565        NaN
593       55.0
630       51.0
789       83.0
806       67.0
836       90.0
842       78.0
953       64.0
994       96.0
            Series_Title Released_Year  Runtime  Genre  IMDB_Rating  \
86             Andhadhun          2018      139  Crime          8.3
113   A Clockwork Orange          1971      136  Crime          8.3
437  Anatomy of a Murder          1959      161  Crime          8.0
664         A Bronx Tale          1993      121  Crime          7.8

            Director               Star1  No_of_Votes       Gross  Metascore
86   Sriram Raghavan  Ayushmann Khurrana        71875   1373943.0        NaN
113  Stanley Kubrick    Malcolm McDowell       757904   6207725.0       77.0
437   Otto Preminger       James Stewart        59847  11900000.0       95.0
664   Robert De Niro      Robert De Niro       128171  17266971.0       80.0
                       Series_Title Released_Year  Runtime  Genre  \
40               American History X          1998      119  Drama
74                   Apocalypse Now          1979      147  Drama
76                            Anand          1971      122  Drama
98                  American Beauty          1999      122  Drama
190                   All About Eve          1950      138  Drama
199                       Ah-ga-ssi          2016      145  Drama
244                   Amores perros          2000      154  Drama
307                 Ace in the Hole          1951      111  Drama
324                         Airlift          2016      130  Drama
408           Au revoir les enfants          1987      104  Drama
447        A Streetcar Named Desire          1951      122  Drama
461  All Quiet on the Western Front          1930      152  Drama
476                         Arrival          2016      116  Drama
483                           Amour          2012      127  Drama
534                   All That Jazz          1979      123  Drama
619           Auf der anderen Seite          2007      122  Drama
620                       Atonement          2007      123  Drama
804                   Abre los ojos          1997      119  Drama
813               A Little Princess          1995       97  Drama
824                  A Few Good Men          1992      138  Drama
903                  A Star Is Born          2018      136  Drama

     IMDB_Rating               Director                   Star1  No_of_Votes  \
40           8.5              Tony Kaye           Edward Norton      1034705
74           8.4   Francis Ford Coppola            Martin Sheen       606398
76           8.4   Hrishikesh Mukherjee           Rajesh Khanna        30273
98           8.3             Sam Mendes            Kevin Spacey      1069738
190          8.2   Joseph L. Mankiewicz             Bette Davis       120539
199          8.1         Chan-wook Park             Kim Min-hee       113649
244          8.1  Alejandro G. Iñárritu       Emilio Echevarría       223741
307          8.1           Billy Wilder            Kirk Douglas        31568
324          8.0             Raja Menon            Akshay Kumar        52897
408          8.0            Louis Malle         Gaspard Manesse        31163
447          8.0             Elia Kazan            Vivien Leigh        99182
461          8.0        Lewis Milestone               Lew Ayres        57318
476          7.9       Denis Villeneuve               Amy Adams       594181
483          7.9         Michael Haneke  Jean-Louis Trintignant        93090
534          7.9              Bob Fosse            Roy Scheider        28223
619          7.8             Fatih Akin             Baki Davrak        30827
620          7.8             Joe Wright         Keira Knightley       251370
804          7.7     Alejandro Amenábar         Eduardo Noriega        64082
813          7.7         Alfonso Cuarón         Liesel Matthews        32236
824          7.7             Rob Reiner              Tom Cruise       235388
903          7.6         Bradley Cooper               Lady Gaga       334312

           Gross  Metascore
40     6719864.0       62.0
74    83471511.0       94.0
76   472504446.0        NaN
98   130096601.0       84.0
190      10177.0       98.0
199    2006788.0       84.0
244    5383834.0       83.0
307    3969893.0       72.0
324   96927481.0        NaN
408    4542825.0       88.0
447    8000000.0       97.0
461    3270000.0       91.0
476  100546139.0       81.0
483    6739492.0       94.0
534   37823676.0       72.0
619     741283.0       85.0
620   50927067.0       85.0
804     368234.0        NaN
813   10019307.0       83.0
824  141340178.0       62.0
903  215288866.0       88.0
Empty DataFrame
Columns: [Series_Title, Released_Year, Runtime, Genre, IMDB_Rating, Director, Star1, No_of_Votes, Gross, Metascore]
Index: []
Empty DataFrame
Columns: [Series_Title, Released_Year, Runtime, Genre, IMDB_Rating, Director, Star1, No_of_Votes, Gross, Metascore]
Index: []
Empty DataFrame
Columns: [Series_Title, Released_Year, Runtime, Genre, IMDB_Rating, Director, Star1, No_of_Votes, Gross, Metascore]
Index: []
   Series_Title Released_Year  Runtime   Genre  IMDB_Rating      Director  \
75        Alien          1979      117  Horror          8.4  Ridley Scott

               Star1  No_of_Votes       Gross  Metascore
75  Sigourney Weaver       787806  78900000.0       89.0
Empty DataFrame
Columns: [Series_Title, Released_Year, Runtime, Genre, IMDB_Rating, Director, Star1, No_of_Votes, Gross, Metascore]
Index: []
Empty DataFrame
Columns: [Series_Title, Released_Year, Runtime, Genre, IMDB_Rating, Director, Star1, No_of_Votes, Gross, Metascore]
Index: []
Empty DataFrame
Columns: [Series_Title, Released_Year, Runtime, Genre, IMDB_Rating, Director, Star1, No_of_Votes, Gross, Metascore]
Index: []

C:\Users\susov\AppData\Local\Temp\ipykernel_7676\1195506619.py:5: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  genre.apply(hoo)

Empty DataFrame
Columns: []
Index: []